name: unittests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      max-parallel: 1
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.20"
      - name: Install dependencies
        run: uv sync --frozen --all-extras
      - name: Format with ruff
        run: uv run ruff format --diff
      - name: Lint with ruff
        run: uv run ruff check --diff
      - name: Type check with pyright
        run: uv run pyright
      - name: Test API
        run: |
          uv run pytest -cov-report=xml --cov=geckoterminal_api tests/test_api.py -v
      - name: Test Exceptions and Validation
        run: |
          uv run pytest -cov-report=xml --cov=geckoterminal_api tests/test_exceptions.py --cov-append -v
          uv run pytest -cov-report=xml --cov=geckoterminal_api tests/test_validation.py --cov-append -v
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Test Async API
        run: |
          uv run pytest -cov-report=xml --cov=geckoterminal_api tests/test_async_api.py --cov-append -v
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}